### ISSUE TITLE
[FEATURE] convertAutoOrientationToHumanReadableString

### ISSUE THREAD

**Issue by 321paranoiawhy** [gladiuscode/react-native-orientation-director#26]
Since already have `convertOrientationToHumanReadableString`, but does not have `convertAutoOrientationToHumanReadableString`, we can provide this util to convert `AutoOrientation` to human readable string.

We can achive this by add more key-value pairs in `_localizedStringProvider` and update `InterfaceOrientationToLocalizedStringProvider` and `convertOrientationToHumanReadableString` param type from `Orientation` to `Orientation | AutoOrientation`, or add function `convertAutoOrientationToHumanReadableString`, but I suggest the formmer.

**Comment by gladiuscode** [comment]
Hi @321paranoiawhy, thank you for your suggestion!

I think that it does makes sense and we should add it, however I believe that the best approach to it should be the latter for the following reasons:

1. Since Orientation and AutoOrientation are both enums with overlapping values, updating convertOrientationToHumanReadableString to accept them both would break the logic because at the end of the day, we are using javascript and we would have an object with the same keys;
2. Having two separate functions is more concise and cleaner, we separate the logic and avoid overlaps;

What do you think about it?

I'll look into it as soon as I get a working mac to actually code it.

**Comment by 321paranoiawhy** [comment]
> Hi @321paranoiawhy, thank you for your suggestion!
> 
> I think that it does makes sense and we should add it, however I believe that the best approach to it should be the latter for the following reasons:
> 
> 1. Since `Orientation` and `AutoOrientation` are both enums with overlapping values, updating `convertOrientationToHumanReadableString` to accept them both would break the logic because at the end of the day, we are using Javascript and we would have an object with the same keys;
> 2. Having two separate functions is more concise and cleaner, we separate the logic and avoid overlaps;
> 
> What do you think about it?
> 
> I'll look into it as soon as I get a working mac to actually code it.

the second solution should be ok in my opinion, use `convertAutoOrientationToHumanReadableString` or not is up to u, lol

**Comment by gladiuscode** [comment]
> > Hi @321paranoiawhy, thank you for your suggestion!
> > I think that it does makes sense and we should add it, however I believe that the best approach to it should be the latter for the following reasons:
> > 
> > 1. Since `Orientation` and `AutoOrientation` are both enums with overlapping values, updating `convertOrientationToHumanReadableString` to accept them both would break the logic because at the end of the day, we are using Javascript and we would have an object with the same keys;
> > 2. Having two separate functions is more concise and cleaner, we separate the logic and avoid overlaps;
> > 
> > What do you think about it?
> > I'll look into it as soon as I get a working mac to actually code it.
> 
> the second solution should be ok in my opinion, use `convertAutoOrientationToHumanReadableString` or not is up to u, lol

Hi @321paranoiawhy,
I've managed to find time to implement this feature.

Let me know if it covers your suggestions and if so, i'll merge it right away.

Thanks!

**Comment by 321paranoiawhy** [comment]
> > > Hi @321paranoiawhy, thank you for your suggestion!
> > > I think that it does makes sense and we should add it, however I believe that the best approach to it should be the latter for the following reasons:
> > > 
> > > 1. Since `Orientation` and `AutoOrientation` are both enums with overlapping values, updating `convertOrientationToHumanReadableString` to accept them both would break the logic because at the end of the day, we are using Javascript and we would have an object with the same keys;
> > > 2. Having two separate functions is more concise and cleaner, we separate the logic and avoid overlaps;
> > > 
> > > What do you think about it?
> > > I'll look into it as soon as I get a working mac to actually code it.
> > 
> > 
> > the second solution should be ok in my opinion, use `convertAutoOrientationToHumanReadableString` or not is up to u, lol
> 
> Hi @321paranoiawhy, I've managed to find time to implement this feature.
> 
> Let me know if it covers your suggestions and if so, i'll merge it right away.
> 
> Thanks!

Awesome, I think you can merge it and I may test it later on my android physical device, and I will inform u as soon as possible.
